#!/usr/bin/env python3
"""
Calibrate the AST model's index -> activity mapping using the real necklace.

The checkpoint only has LABEL_0..5 with unknown meaning. This records a few
seconds of each activity from the necklace mic, asks the running server which
index each activity fires, and writes that mapping into labels.json (then
hot-reloads the server).

Run with a Python that has `bleak` (the system python3 here does):
    python3 calibrate.py [server_url]

Requirements:
  - Nuna server running (default http://127.0.0.1:8000)
  - Necklace powered and NOT connected to the phone (bleak needs the BLE link)

Edit ACTIVITIES below to match what you can actually perform. `eating=True`
marks food-intake classes (drives the app's eating indicator).
"""
import asyncio
import base64
import json
import sys
import time
import urllib.request
from collections import defaultdict
from pathlib import Path

from bleak import BleakScanner, BleakClient

SVC = "19b10000-e8f2-537e-4f6c-d104768a1214"
AUD = "19b10001-e8f2-537e-4f6c-d104768a1214"
CTL = "19b10002-e8f2-537e-4f6c-d104768a1214"

SERVER = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:8000"
REC_SEC = 10
LABELS_PATH = Path(__file__).with_name("labels.json")

# (display name, is-eating, on-screen instruction). Add/remove to match your model.
ACTIVITIES = [
    ("Silence",    False, "Stay quiet — no eating, minimal noise"),
    ("Chewing",    True,  "Chew food or gum steadily near the necklace"),
    ("Drinking",   True,  "Take sips of water and swallow"),
    ("Swallowing", True,  "Swallow repeatedly (dry swallows ok)"),
    ("Talking",    False, "Talk / read aloud normally"),
]


def classify(pcm: bytes) -> dict:
    body = json.dumps({"pcm_b64": base64.b64encode(pcm).decode()}).encode()
    req = urllib.request.Request(
        f"{SERVER}/classify_b64", data=body, headers={"Content-Type": "application/json"}
    )
    return json.load(urllib.request.urlopen(req, timeout=60))


async def record(client: BleakClient, seconds: int) -> bytes:
    buf = bytearray()
    await client.start_notify(AUD, lambda _, d: buf.extend(d))
    await client.write_gatt_char(CTL, b"\x01", response=True)
    await asyncio.sleep(seconds)
    await client.write_gatt_char(CTL, b"\x00", response=True)
    await client.stop_notify(AUD)
    return bytes(buf)


async def main():
    print(f"[calib] server={SERVER}  {REC_SEC}s per activity")
    print("[calib] scanning for necklace…")
    dev = None
    for _, (d, a) in (await BleakScanner.discover(timeout=8, return_adv=True)).items():
        if SVC in [u.lower() for u in (a.service_uuids or [])]:
            dev = d
            break
    if not dev:
        print("[calib] necklace not found. Powered? Disconnected from the phone?")
        return

    async with BleakClient(dev) as c:
        print("[calib] connected. Follow the prompts.\n")
        # index -> {name, eating, best_prob}
        winners: dict[int, dict] = {}
        for name, eating, instr in ACTIVITIES:
            input(f"  >> {name}: {instr}\n     Press Enter, then DO IT for {REC_SEC}s…")
            for n in (3, 2, 1):
                print(f"     {n}…", end=" ", flush=True)
                time.sleep(1)
            print("GO")
            pcm = await record(c, REC_SEC)
            r = classify(pcm)
            idx = r["top"]["index"]
            prob = r["top"]["prob"]
            print(f"     -> index {idx}  prob {prob:.2f}  rms {r.get('rms')}  "
                  f"probs={ {k: round(v,2) for k,v in r['probs'].items()} }\n")
            # keep the activity that fires an index most strongly
            if idx not in winners or prob > winners[idx]["prob"]:
                winners[idx] = {"name": name, "eating": eating, "prob": prob}

    # build labels.json (unseen indices stay LABEL_x / non-eating)
    classes = {}
    for i in range(6):
        if i in winners:
            classes[str(i)] = {"name": winners[i]["name"], "eating": winners[i]["eating"]}
        else:
            classes[str(i)] = {"name": f"LABEL_{i}", "eating": False}
    out = {"_comment": "Generated by calibrate.py from real necklace recordings.", "classes": classes}
    LABELS_PATH.write_text(json.dumps(out, indent=2))
    print(f"[calib] wrote {LABELS_PATH}:")
    print(json.dumps(classes, indent=2))

    try:
        req = urllib.request.Request(f"{SERVER}/reload_labels", data=b"", method="POST")
        print("[calib] hot-reloaded server:", json.load(urllib.request.urlopen(req, timeout=10))["labels"])
    except Exception as e:
        print(f"[calib] could not hot-reload ({e}); restart the server to apply.")


if __name__ == "__main__":
    asyncio.run(main())
